"""Render deterministico di una scheda Markdown + frontmatter YAML.

Regole:
- YAML ordinato alfabeticamente (sort_keys=True)
- nessun timestamp
- default_flow_style=False, allow_unicode=True
- newline Unix LF
- nessun trailing whitespace
"""
from __future__ import annotations

from typing import Any

import yaml


GENERATED_BANNER = (
    "<!-- GENERATED by tools/build_world.py — DO NOT EDIT.\n"
    "     Source: content/grafo/story_graph_v0_3_0.json, "
    "content/docs/ISOLA_TRE_VENTI_BIBLE_v2.md, "
    "content/worldbuilding/GLOSSARIO_ISOLA.md -->\n"
)


def render_card(frontmatter: dict[str, Any], title: str, body: str) -> str:
    """Ritorna la scheda Markdown completa come stringa, con newline finale.

    Il corpo `body` è prosa pubblica già pulita (no label framework).
    """
    yaml_block = yaml.safe_dump(
        frontmatter,
        sort_keys=True,
        default_flow_style=False,
        allow_unicode=True,
        width=1000,
    ).rstrip("\n")

    body_clean = body.strip()

    parts = [
        GENERATED_BANNER,
        "---\n",
        yaml_block + "\n",
        "---\n",
        "\n",
        f"# {title}\n",
        "\n",
        body_clean + "\n",
    ]
    return "".join(parts)
